language: ruby
cache: bundler
sudo: false
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - truffleruby
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/sinatra.gemfile
matrix:
  allow_failures:
    # https://github.com/rails/rails/pull/37504 should fix
    - rvm: 2.7.0
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.7.0
      gemfile: gemfiles/rails_6.0.gemfile
  exclude:
    - rvm: 2.4.9
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.7.0-preview2
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.7.0
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.7.0
      gemfile: gemfiles/rails_5.1.gemfile
    # truffleruby does not seem to work with Rails
    - rvm: truffleruby
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: truffleruby
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: truffleruby
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: truffleruby
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: truffleruby
      gemfile: gemfiles/rails_6.0.gemfile
before_install:
  # Bundler 2.x is supported for Rails > 4.2
  - ( [[ "$BUNDLE_GEMFILE" =~ rails_4.2.gemfile$ ]] && gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler && gem install bundler -v '< 2' ) || true
script:
  - bundle exec rspec
addons:
  code_climate:
    repo_token: e233a382471f480a061ac3098edadbb91cee8129e0938973aeb2aa8d84a0a93b
after_success:
  - bundle exec codeclimate-test-reporter
